from __future__ import annotations

import sys
import importlib
import sqlite3
import time
from pathlib import Path
from typing import Awaitable, Callable, Dict, List

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.responses import Response
import uvicorn


BASE_DIR = Path(__file__).resolve().parents[2]

# Make "src" importable when main.py is executed directly.
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))


# ============================================================
# DATABASE
# ============================================================

DB_PATH = BASE_DIR / "db" / "nifty100.db"

APP_VERSION = "1.0.0"

APP_START_TIME = time.time()




# ============================================================
# DATABASE SCHEMA
# ============================================================

# These names MUST match the actual SQLite database schema.
SCHEMA_TABLES: List[str] = [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "financial_ratios",
    "sectors",
    "peer_groups",
    "peer_percentiles",
    "valuation",
    "documents",
]



#
ROUTER_MODULES: List[str] = [
    "companies",
    "screener",
    "sectors",
    "peers",
    "valuation",
    "portfolio",
    "documents",
]


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="Financial Analytics API v1.0",
    description=(
        "REST API for the Nifty 100 Financial Intelligence Platform."
    ),
    version=APP_VERSION,
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# REQUEST LOGGING MIDDLEWARE
# ============================================================

@app.middleware("http")
async def log_requests(
    request: Request,
    call_next: Callable[[Request], Awaitable[Response]],
) -> Response:
    """
    Log HTTP method, request path, status code and latency.

    Parameters
    ----------
    request:
        Incoming HTTP request.

    call_next:
        Next middleware / endpoint in the FastAPI pipeline.

    Returns
    -------
    Response
        Response generated by the downstream endpoint.
    """

    start = time.perf_counter()

    response = await call_next(request)

    latency_ms = (time.perf_counter() - start) * 1000

    print(
        f"[{request.method}] "
        f"[{request.url.path}] "
        f"[{response.status_code}] "
        f"[{latency_ms:.2f}ms]"
    )

    return response


# ============================================================
# DATABASE HELPERS
# ============================================================

def get_db_row_counts(
    db_path: Path,
    tables: List[str],
) -> Dict[str, int]:
    """
    Return row counts for the requested database tables.

    If a table does not exist, its count is reported as -1.

    Parameters
    ----------
    db_path:
        SQLite database path.

    tables:
        List of table names.

    Returns
    -------
    Dict[str, int]
        Mapping of table name -> row count.
    """

    counts: Dict[str, int] = {}

    if not db_path.exists():
        return {table: -1 for table in tables}

    with sqlite3.connect(str(db_path)) as conn:
        cursor = conn.cursor()

        for table in tables:

            try:
                # Table names come only from SCHEMA_TABLES,
                # not from user input.
                cursor.execute(
                    f"SELECT COUNT(*) FROM [{table}]"
                )

                result = cursor.fetchone()

                counts[table] = int(result[0]) if result else 0

            except sqlite3.OperationalError:
                counts[table] = -1

    return counts


def check_database_connection(db_path: Path) -> bool:
    """
    Check whether the SQLite database can be opened successfully.

    Returns
    -------
    bool
        True if the database can be opened, otherwise False.
    """

    if not db_path.exists():
        return False

    try:
        with sqlite3.connect(str(db_path)) as conn:
            conn.execute("SELECT 1")

        return True

    except sqlite3.Error:
        return False


# ============================================================
# ROUTER REGISTRATION
# ============================================================

def _register_routers(
    fastapi_app: FastAPI,
    module_names: List[str],
) -> None:
    """
    Dynamically import and register API routers.

    Each router module is expected to expose:

        router = APIRouter(...)

    Routers that have not yet been created are skipped.

    Parameters
    ----------
    fastapi_app:
        FastAPI application instance.

    module_names:
        Router module names under src.api.routers.
    """

    for module_name in module_names:

        module_path = f"src.api.routers.{module_name}"

        try:
            module = importlib.import_module(module_path)

        except ModuleNotFoundError as exc:

            # Only skip the router if the router module itself
            # does not exist.
            if exc.name == module_path:
                print(
                    f"[INFO] Router not implemented yet: "
                    f"{module_path}"
                )
                continue

            # If the router exists but one of its dependencies
            # is missing, expose the actual error.
            raise

        if not hasattr(module, "router"):
            print(
                f"[WARNING] Router module has no 'router': "
                f"{module_path}"
            )
            continue

        fastapi_app.include_router(
            module.router,
            prefix="/api/v1",
        )

        print(
            f"[INFO] Registered router: "
            f"/api/v1/{module_name}"
        )


# Register available routers.
_register_routers(app, ROUTER_MODULES)


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get(
    "/api/v1/health",
    tags=["Health"],
)
def get_health() -> Dict[str, object]:
    """
    Health check endpoint.

    Returns database connectivity, table row counts,
    API uptime and application version.
    """

    db_connected = check_database_connection(DB_PATH)

    return {
        "status": "ok" if db_connected else "degraded",
        "database": {
            "connected": db_connected,
            "path": str(DB_PATH),
        },
        "db_row_counts": get_db_row_counts(
            DB_PATH,
            SCHEMA_TABLES,
        ),
        "uptime_seconds": round(
            time.time() - APP_START_TIME,
            2,
        ),
        "version": APP_VERSION,
    }


# ============================================================
# ROOT ENDPOINT
# ============================================================

@app.get(
    "/",
    tags=["Health"],
)
def root() -> Dict[str, str]:
    """
    Root API endpoint.
    """

    return {
        "message": "Financial Analytics API is running",
        "version": APP_VERSION,
        "docs": "/docs",
        "health": "/api/v1/health",
    }


# ============================================================
# APPLICATION ENTRYPOINT
# ============================================================

if __name__ == "__main__":
    

    uvicorn.run(
        "src.api.main:app",
        host="127.0.0.1",
        port=8000,
        reload=True,
    )

